#ifndef LED_MATRIX_CONSTANTS_H
#define LED_MATRIX_CONSTANTS_H

// Address mappings
#define ADDR_NOP       0x00U
// TOP = Led Matrix writing on PCB (row0)
// BOTTOM = array on PCB (row7)
// LEFT = DIN side
// RIGHT = DOUT side, writing a 1 in rowX will place a dot in the right most position
#define ADDR_ROW0      0x01U
#define ADDR_ROW1      0x02U
#define ADDR_ROW2      0x03U
#define ADDR_ROW3      0x04U
#define ADDR_ROW4      0x05U
#define ADDR_ROW5      0x06U
#define ADDR_ROW6      0x07U
#define ADDR_ROW7      0x08U
#define ADDR_DECODE    0x09U
#define ADDR_INTENSITY 0x0AU
#define ADDR_SCANLIMIT 0x0BU
#define ADDR_SHUTDOWN  0x0CU
#define ADDR_DISPTEST  0x0FU
// Alternative namses: 7-segment names
#define ADDR_DIGIT0    ADDR_ROW0
#define ADDR_DIGIT1    ADDR_ROW1
#define ADDR_DIGIT2    ADDR_ROW2
#define ADDR_DIGIT3    ADDR_ROW3
#define ADDR_DIGIT4    ADDR_ROW4
#define ADDR_DIGIT5    ADDR_ROW5
#define ADDR_DIGIT6    ADDR_ROW6
#define ADDR_DIGIT7    ADDR_ROW7
#define ADDR_BRIGHTNESS  ADDR_INTENSITY

// Data constants
#define DATA_SHUTDOWN_ON   0x00U
#define DATA_SHUTDOWN_OFF  0x01U
// Decode, set uses binary format e.g. 0b111 will set digit 7 for 7-segment display
// otherwise each bit refers to a different segment/line
#define DATA_DECODE_NONE           0x00U
#define DATA_DECODE_ALL_ROWS       0xFFU
#define DATA_DECODE_SET_ROWS(x)    (x)
#define DATA_INTENSITY_LEVEL1        0x01U // lowest brightness
#define DATA_INTENSITY_LEVEL2        0x02U
#define DATA_INTENSITY_LEVEL3        0x03U
#define DATA_INTENSITY_LEVEL4        0x04U
#define DATA_INTENSITY_LEVEL5        0x05U
#define DATA_INTENSITY_LEVEL6        0x06U
#define DATA_INTENSITY_LEVEL7        0x07U
#define DATA_INTENSITY_LEVEL8        0x08U
#define DATA_INTENSITY_LEVEL9        0x09U
#define DATA_INTENSITY_LEVEL10       0x0AU
#define DATA_INTENSITY_LEVEL11       0x0BU
#define DATA_INTENSITY_LEVEL12       0x0CU
#define DATA_INTENSITY_LEVEL13       0x0DU
#define DATA_INTENSITY_LEVEL14       0x0EU
#define DATA_INTENSITY_LEVEL15       0x0FU // highest brightness
#define DATA_SCANLIMIT_1_ROWS_MAX    0x00U // row 0
#define DATA_SCANLIMIT_2_ROWS_MAX    0x01U // row 0-1
#define DATA_SCANLIMIT_3_ROWS_MAX    0x02U // row 0-2
#define DATA_SCANLIMIT_4_ROWS_MAX    0x03U // row 0-3
#define DATA_SCANLIMIT_5_ROWS_MAX    0x04U // row 0-4
#define DATA_SCANLIMIT_6_ROWS_MAX    0x05U // row 0-5
#define DATA_SCANLIMIT_7_ROWS_MAX    0x06U // row 0-6
#define DATA_SCANLIMIT_8_ROWS_MAX    0x07U // row 0-7
#define DATA_DISPTEST_ON           0x01U
#define DATA_DISPTEST_OFF          0x00U
// Alternative names
#define DATA_DECODE_ALL_DIGITS     DATA_DECODE_ALL_ROWS
#define DATA_DECODE_SET_DIGITS(x)  DATA_DECODE_SET_ROWS(x)
#define DATA_SCANLIMIT_1_ROW_MAX   DATA_SCANLIMIT_1_ROWS_MAX
#define DATA_SCANLIMIT_TO_ROW0     DATA_SCANLIMIT_1_ROWS_MAX
#define DATA_SCANLIMIT_TO_ROW1     DATA_SCANLIMIT_2_ROWS_MAX
#define DATA_SCANLIMIT_TO_ROW2     DATA_SCANLIMIT_3_ROWS_MAX
#define DATA_SCANLIMIT_TO_ROW3     DATA_SCANLIMIT_4_ROWS_MAX
#define DATA_SCANLIMIT_TO_ROW4     DATA_SCANLIMIT_5_ROWS_MAX
#define DATA_SCANLIMIT_TO_ROW5     DATA_SCANLIMIT_6_ROWS_MAX
#define DATA_SCANLIMIT_TO_ROW6     DATA_SCANLIMIT_7_ROWS_MAX
#define DATA_SCANLIMIT_TO_ROW7     DATA_SCANLIMIT_8_ROWS_MAX
#define DATA_BRIGHTNESS_LEVEL1     DATA_INTENSITY_LEVEL1 // lowest brightness
#define DATA_BRIGHTNESS_LEVEL2     DATA_INTENSITY_LEVEL2
#define DATA_BRIGHTNESS_LEVEL3     DATA_INTENSITY_LEVEL3
#define DATA_BRIGHTNESS_LEVEL4     DATA_INTENSITY_LEVEL4
#define DATA_BRIGHTNESS_LEVEL5     DATA_INTENSITY_LEVEL5
#define DATA_BRIGHTNESS_LEVEL6     DATA_INTENSITY_LEVEL6
#define DATA_BRIGHTNESS_LEVEL7     DATA_INTENSITY_LEVEL7
#define DATA_BRIGHTNESS_LEVEL8     DATA_INTENSITY_LEVEL8
#define DATA_BRIGHTNESS_LEVEL9     DATA_INTENSITY_LEVEL9
#define DATA_BRIGHTNESS_LEVEL10    DATA_INTENSITY_LEVEL10
#define DATA_BRIGHTNESS_LEVEL11    DATA_INTENSITY_LEVEL11
#define DATA_BRIGHTNESS_LEVEL12    DATA_INTENSITY_LEVEL12
#define DATA_BRIGHTNESS_LEVEL13    DATA_INTENSITY_LEVEL13
#define DATA_BRIGHTNESS_LEVEL14    DATA_INTENSITY_LEVEL14
#define DATA_BRIGHTNESS_LEVEL15    DATA_INTENSITY_LEVEL15 // highest brightness

enum AddrRows {
	AddrRow0 = ADDR_ROW0
	, AddrRow1
	, AddrRow2
	, AddrRow3
	, AddrRow4
	, AddrRow5
	, AddrRow6
	, AddrRow7
};

#endif /* LED_MATRIX_CONSTANTS_H */
